version: '3.1'

services:
  db:
    restart: always
    networks:
      - default
      - db-net

  nginx:
    image: nginx
    container_name: achacasa_nginx
    restart: always
    volumes:
      - ./config:/etc/nginx/conf.d
      - staticfiles:/static
    depends_on:
      - web
    labels:
      - 'traefik.http.routers.achacasa_nginx.rule=Host(`achacasa.online`)'
      - 'traefik.enable=true'

  web:
    build: .
    container_name: achacasa_web
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - staticfiles:/code/static
    depends_on:
      - db
    expose:
      - '8000'

volumes:
  staticfiles:

networks:
  db-net:
    external: true
