version: '3.1'

services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: achacasa
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql

  nginx:
    image: nginx
    restart: always
    ports:
      - '8000:8000'
    volumes:
      - ./config:/etc/nginx/conf.d
      - ./static:/static
    depends_on:
      - web

  web:
    build: .
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    expose:
      - '8000'

  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'
    links:
      - db

volumes:
  dbdata:
