version: '3.1'

services:
  db:
    restart: always

  adminer:
    restart: always

  nginx:
    image: nginx
    restart: always
    ports:
      - '8000:8000'
    volumes:
      - ./config:/etc/nginx/conf.d
      - staticfiles:/static
    depends_on:
      - web

  web:
    build: .
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - staticfiles:/code/static
    depends_on:
      - db
    expose:
      - '8000'

volumes:
  staticfiles:
