# Generated by Django 2.1.4 on 2019-03-20 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'cities',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('bedrooms', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('type', models.CharField(max_length=20)),
                ('document', models.CharField(blank=True, max_length=100, null=True)),
                ('evaluation_value', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('minimum_value', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('sale_value', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('private_area', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('site_area', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('total_area', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=12, null=True)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=12, null=True)),
                ('is_occupied', models.BooleanField(null=True)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.City')),
            ],
            options={
                'verbose_name_plural': 'properties',
            },
        ),
        migrations.AddField(
            model_name='photo',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.Property'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.Property'),
        ),
    ]
